import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/Components/Layout";
import Contaxt_api from "@/Components/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Homeland",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Contaxt_api>
          <Layout>{children}</Layout>
        </Contaxt_api>
      </body>
    </html>
  );
}
